### ISSUE TITLE
test4 vertical spacing wrong?

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#10]
It seems the vertical positioning of test4 is not in line with the rendering of test1; the two rows of text are spaced out much wider and the whole (red) paragraph is extended compared to test1.
![test4](https://cloud.githubusercontent.com/assets/4577613/8286653/1aab28ac-190b-11e5-907a-3fb49e8f6fcc.png)

**Comment by SoleneChiche** [comment]
I'll look into. It is indeed a CSS related bug.

**Comment by frans-ebu** [comment]
txn
