### ISSUE TITLE
test8 RGBA colour rendering fails

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#11]

**Comment by SoleneChiche** [comment]
Yes it is normal. 8-decimal hexadecimal RGBA notation is not yet supported.
I will add a converter in the parser.

**Comment by frans-ebu** [comment]
test8 fails for me:
- [ ] The text is not white
  ![image1](https://cloud.githubusercontent.com/assets/4577613/8647106/6284e794-2955-11e5-8864-c9e27ecf9ab4.jpg)

**Comment by SoleneBuet** [comment]
This is what I get for test 8: 
<img width="1440" alt="capture d ecran 2015-07-13 a 13 01 15" src="https://cloud.githubusercontent.com/assets/9998409/8648274/8c99c608-295f-11e5-87f3-2bc6460d1a75.png">

**Comment by SoleneChiche** [comment]
This is what I get for test 8:
<img width="1440" alt="capture d ecran 2015-07-13 a 13 01 19" src="https://cloud.githubusercontent.com/assets/9998409/8648295/b458e58e-295f-11e5-9b16-62acaf1a28de.png">

**Comment by frans-ebu** [comment]
agreed (different test file), but the text colour is still not white.

**Comment by SoleneChiche** [comment]
Okay, can you check with the last commit please?

**Comment by frans-ebu** [comment]
perfect, tnx.
