### ISSUE TITLE
Time-plan and resources for bringing this to dash-if/dash.js

### ISSUE THREAD

**Issue by TobbeMobiTV** [ebu/dash.js#15]
I saw this at the f2f meeting in Berlin in May and this is a very interesting piece of work.

Is there any plan and time-frame for bringing this to main repo for dash.js?
Are any extra resources needed, and then, approximately how much?

Even if it is not fully complete/compliant with EBU-TT-D, it may be good to incorporate it since there is no styling or positioning support at all for TTML subtitles in the dashif/dash.js at present.

**Comment by SoleneChiche** [comment]
> Is there any plan and time-frame for bringing this to main repo for dash.js?
> Not yet, but if possible, before I leave by the end of August.
> 
> Are any extra resources needed, and then, approximately how much?
> For now, test material and tools to generate them (MP4Box has its limitations). Otherwise help is much needed from experienced people in integrating features in dash.js.

I think we'll sort this out with the webconf on Wednesday.

Thank you for your interest!
