### ISSUE TITLE
Play button inverted

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#16]
The play button shows as 'play' after auto-start (should be 'paused').

**Comment by frans-ebu** [comment]
Note: this is not a prio to fix, as the player is just to demo the EBU-TT-D parsing/rendering.

**Comment by SoleneChiche** [comment]
I did a quick fix, as for now I can't access the autoplay information from the dash player.

**Comment by frans-ebu** [comment]
tnx
