### ISSUE TITLE
unicodebidi embed, rtl fails (test 13)

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#19]
text is shown left to right instead of right to left

**Comment by SoleneChiche** [comment]
I'm not sure this is the result intended actually:
https://css-tricks.com/almanac/properties/u/unicode-bidi/
http://www.startyourdev.com/css/style-css-unicode-bidi

But maybe it is not also the best testing material.

**Comment by frans-ebu** [comment]
Yes, let's improve the test material first. Also see e.g. http://www.iamcal.com/understanding-bidirectional-text/

**Comment by frans-ebu** [comment]
Another one: http://www.w3.org/International/articles/inline-bidi-markup/uba-basics

**Comment by frans-ebu** [comment]
I think it is ok now (test10, -11, -12, 13 tested with the new test material).
