### ISSUE TITLE
Region size changes as function of padding [tests 14 15 23 24 25  26]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#20]
Setting padding grows the region.

test14, test15, test23, test24, test25, test26

**Comment by SoleneChiche** [comment]
It should be a quick fix. Except if it collide with other features and their behavior...

**Comment by SoleneChiche** [comment]
It should be resolved. Could you check please?

**Comment by frans-ebu** [comment]
ok, tnx.
