### ISSUE TITLE
overflow = visible grows region [test 36]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#21]
The first subtitle in test 36 (wrap, overflow=visible) fails.

The text with overflow set to 'visible' grows the region, instead of making the text go over the region.
![1](https://cloud.githubusercontent.com/assets/4577613/8673406/8d4afc70-2a36-11e5-8b4a-346328f0dfb3.jpg)

**Comment by SoleneChiche** [comment]
To not go grow the region, you should pair with wrapOption, nowrap?

**Comment by frans-ebu** [comment]
Not sure what you mean. My understanding is that the region is fixed, but that wrap/overflow can lead to text going beyond the region, however you would not expect that to happen at the beginning (top in this case) of the region?!

**Comment by SoleneChiche** [comment]
I mean that by default behavior, if overflow is visible, it will extends the region as wrap option is by default wrapping the text. Maybe a matrix of the behavior expected depending on wrap option could help.

**Comment by frans-ebu** [comment]
I believe:
- The region itself is NEVER changed, but...;
- When wrapoption == wrap, the parser wraps the lines, trying to fit them into the original region (by adding linebreaks);
- When overflow == visible, it calculates AS IF the region has a fixed origin, but unconstrained height & width (but is still constrained by the parent, e.g. root container). This extra space can be used to extend the newly added (wrapped) lines beyond the original region's edge.

I guess it is legal to draw new lines that cross not only the right, but also the BOTTOM part of the region, but I would expect they may not come before or above the region.

**Comment by andreastai** [comment]
Right. The region is fixed and here is no way to extend it. This is important when you apply background color to the region. When the text is drawn outside the region the background color would not extend. Only the text will be shown. This is very similiar to the html behaviour (I can post a sample). Text can overflow on both sides of the region (right then bottom for left-to-right inline writing direction and top to bottom block writing direction).

On the other hand it is important to note that the overflow "visible" setting is a kind of error recovery strategy (where the TTML document is authored incorrectly). The way it is specified the display of text is not guaranteed even if overflow is set to visible. You may argue that actually error handling is out scope of the speac and more in the hand of the player/renderer. An author can not expect a specific rendering in the case his document has an implicit layout error. To let the region grow may even be a better solution if the player is able to do this (BTW this is standard behaviour in WebVTT). But this is more a personal opinion ; )

**Comment by SoleneChiche** [comment]
Hello Andreas, 

You say you have an HTML/CSS example you could post? I'm open. It would allow me to resolve it quickly.

Many thanks

**Comment by SoleneChiche** [comment]
Is that close?
<img width="1116" alt="capture d ecran 2015-07-17 a 10 46 59" src="https://cloud.githubusercontent.com/assets/9998409/8743686/3a6cfe62-2c71-11e5-91a1-dbc20ceff6e7.png">

**Comment by frans-ebu** [comment]
I agree we need to improve the testmaterial.

**Comment by SoleneChiche** [comment]
Can you confirm it is ok now?

**Comment by andreastai** [comment]
See below some example code based on W3C School (http://www.w3schools.com/cssref/tryit.asp?filename=trycss_overflow + http://www.w3schools.com/cssref/pr_pos_overflow.asp)

``` html
<!DOCTYPE html>
<html>
<head>
<style>
div.visible {
    background-color: #00FFFF;
    width: 100px;
    height: 100px;
    overflow: visible;
}

div.hidden {
    background-color: #00FF00;
    width: 100px;
    height: 100px;
    overflow: hidden;

}
</style>
</head>
<body>

<p>The overflow property specifies what to do if the content of an element exceeds the size of the element's box.</p>


<p>overflow:visible</p>
<div class="visible">You can use the overflow property when you want to have better control of the layout. The default value is visible.</div>

<p style="margin-top: 100px;">overflow:hidden</p>
<div class="hidden">You can use the overflow property when you want to have better control of the layout. The default value is visible.</div>

</body>
</html>

```

**Comment by nigelmegitt** [comment]
@tairt Are you sure that the value of `tts:displayAlign` isn't relevant? I'm wondering if when `tts:displayAlign="after"` and `tts:overflow="visible"` the overflow should be off the top of the region. I haven't got time to check through the XSL reference from the TTML1 spec right now, but that's the route to go down... Start with http://www.w3.org/TR/ttml1/#style-attribute-displayAlign

**Comment by frans-ebu** [comment]
@nigelmegitt That is what we expect, too (but I did not check the XSL reference in-depth) and what the current code supports.

This issue was due to the test material we used not  being very helpful, as it hid the region (white text with black background). The second version addressed that (red text, transparent background), but does not test the displayalign value in combination with overflow. I'll add some more tests for those cases separately.

**Comment by andreastai** [comment]
@nigelmegitt I didn't intent to say that tts:displayAlign is not relevant for overflow. From which comment did you read that interpretation?

**Comment by nigelmegitt** [comment]
@tairt Only because you mentioned that overflow can happen "on both sides" without mentioning top and bottom and `tts:displayAlign` - I just meant that we need to consider that attribute within the scope of this issue.

**Comment by SoleneChiche** [comment]
So what would be an acceptable material to test wrapOption? It would be a combinaison of wrapOption, overflow and displayAlign?

**Comment by frans-ebu** [comment]
yes, testing for the different combinations.

**Comment by frans-ebu** [comment]
ok, test material for test36 improved and test passed, tnx.
