### ISSUE TITLE
region clips in wrong way when overflow = hidden [test 36]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#22]
Test 36: The region clips (as is expected, because wrap, overflow = hidden), but the content in the region seems to have been moved up, first. What is expected is that the remainder of the content that does not fit the region is clipped, not the beginning of it.
![2](https://cloud.githubusercontent.com/assets/4577613/8673517/74f0a8ea-2a37-11e5-9175-d2200c72718d.jpg)

**Comment by SoleneChiche** [comment]
Yes indeed it's buggy. On the todo!

**Comment by SoleneChiche** [comment]
Is that close?
<img width="1172" alt="capture d ecran 2015-07-17 a 10 48 53" src="https://cloud.githubusercontent.com/assets/9998409/8743716/759ec7cc-2c71-11e5-8654-ff98bd62aac0.png">

**Comment by frans-ebu** [comment]
ok, as discussed we should improve the test-material and remove displayalign = center, tnx

**Comment by SoleneChiche** [comment]
Can you confirm it is ok now?

**Comment by frans-ebu** [comment]
It's ok. tnx.
