### ISSUE TITLE
Inactive region is rendered after seeking [test 45]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#23]
To reproduce:
- play test 45
- seek back to ~ 2 seconds (blue region still shown, but should be inactive before 4 s).
  ![seeking](https://cloud.githubusercontent.com/assets/4577613/8677256/4dda3886-2a4e-11e5-8978-c676a82b83c3.jpg)

**Comment by SoleneChiche** [comment]
I think I've seen it before. I need to check if it is because of the span timings. Thanks.

**Comment by SoleneChiche** [comment]
This should be fixed now.

**Comment by frans-ebu** [comment]
ACK

**Comment by SoleneChiche** [comment]
The thing is even tested, you'll see that the video stops (issue #24). But this issue in particular is resolved.
