### ISSUE TITLE
Playback pauses/stops for [test 45/46]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#24]
It seems to happen at the point where the <span> becomes active? (4 s)

**Comment by SoleneChiche** [comment]
Sorry, where the what becomes active?

**Comment by frans-ebu** [comment]
the span

Sent from my iPhone

On 15.07.2015, at 10:12, "SoleneBuet" <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry, where the what becomes active?

�

## Reply to this email directly or view it on GitHubhttps://github.com/ebu/dash.js/issues/24#issuecomment-121524770.

---

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error, please notify the system manager. This footnote also confirms that this email message has been swept by the mailgateway

---

**Comment by SoleneChiche** [comment]
I'm not sure but it seems like a problem from MP4Box. If there is only one subtitle, it will just receive the first one (ex: if dashed 10000 (10s), it will receive only the first 10secs), and then the video won't work past these 10s...

**Comment by SoleneChiche** [comment]
Even if there are two subtitles, it will stop automatically after the two are passed.

**Comment by SoleneChiche** [comment]
I close this one as it is both related with issues #30 / #31
