### ISSUE TITLE
test47-63.xml does not render

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#25]
Note the test leaves out many things on purpose (to test initial values behaviour) and even does not refer to any style (although it does define one as that is mandatory).

**Comment by SoleneChiche** [comment]
@frans-ebu So for color and background color, what do we want (black on transparent, white on black?)?

**Comment by frans-ebu** [comment]
If not defined by the user:
- background color = TTML 1 initial value = transparent
- color = application dependent (EBU recommends good contrast) -> for this implementation I would choose white

**Comment by SoleneChiche** [comment]
So if both are not defined, white on transparent? I would rather choose a flashy yellow or green...

**Comment by nigelmegitt** [comment]
Cue long debate on what is the least used colour in broadcast video content... Actually I might know someone who knows the answer to that, I'll check.

**Comment by frans-ebu** [comment]
@SoleneBuet I am not guaranteeing it is optimum, but just feel it is the most used colour for subs, so biggest change to get it right, but I'd love to use another facts (stats) based colour recommendation, based on @nigelmegitt 's check!

My simple first guess based on prodution experience (chroma-keying) would be: (bright) green or blue (minimial interference with skin tones for blue and less used in wardrobes for green).

**Comment by frans-ebu** [comment]
Can we have the transparent and whiteimplemented for now, and then make this an 'improvement' issue (not closing it until we have the facts check done)?

**Comment by SoleneChiche** [comment]
This is the case now. Thanks

**Comment by frans-ebu** [comment]
The test renders now, so I will close this one.

**Comment by nigelmegitt** [comment]
Got a partial response - we won't know colour but we might know luminance... A bit more work to be done to get the value though.
