### ISSUE TITLE
multiple region elements / overlapping timing not yet supported [test 2]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#26]

**Comment by SoleneChiche** [comment]
We need to test with NHML

**Comment by SoleneChiche** [comment]
@frans-ebu This should be fixed now, but only with NHML (test2_nhml). Next step is to improve performance issues.

**Comment by frans-ebu** [comment]
tnx

**Comment by TobbeMobiTV** [comment]
Hi Frans and others,

Do you have any test content for EBU-TT-D spanning the different styles that are possible?
A number of TTML files using the different styling would be good. Packaging in mp4 segments is not necessary for testing of styling.
It is then possible to add these files as different “tracks” in some test-video-content like http://vm2.dashif.org/dash/vod/testpic_2s/xml_subs.mpd

Best Regards,

## Torbjörn

Torbjörn Einarsson, Ph.D
Sr Director Technology
MobiTV Sweden AB

Packhusgränd 7, 111 30 Stockholm, Sweden
phone +46 72 20 325 88
email teinarsson@mobitv.com
web www.mobitv.com

NOTICE: This email message and any attachments are for the sole use of the intended recipient(s) and may contain confidential and/or legally privileged information. If you are not an intended recipient or his or her representative, you are hereby notified that any unauthorized review, use, disclosure or distribution is prohibited. If you have received this communication in error please immediately contact the sender by reply email and destroy all copies of the original message and attachments.
