### ISSUE TITLE
foreign metadata influences display [test 3]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#27]
Foreign metadata (as child of the tt:metadata element) currently is not totally ignored. See test3
![image1](https://cloud.githubusercontent.com/assets/4577613/8724083/ff5784d8-2bcf-11e5-976e-f8507ce0e019.jpg)

**Comment by frans-ebu** [comment]
@SoleneBuet  I know you have not implemented this yet, but did the test already to make transparent where we are/not to forget.

**Comment by SoleneChiche** [comment]
Should be fixed now.

**Comment by frans-ebu** [comment]
ok now, tnx
