### ISSUE TITLE
MultiRowAlign / textAlign fails [test 64]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#28]
at least for:

multiRowAlign = auto, textAlign = right (see test64)
![image2](https://cloud.githubusercontent.com/assets/4577613/8724863/32e9d66a-2bd1-11e5-9a10-249c1b3d34ff.jpg)

**Comment by SoleneChiche** [comment]
This should be fixed now.

**Comment by frans-ebu** [comment]
ok, tnx
