### ISSUE TITLE
Multiple style references not supported [test 78]

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#29]
test78

![image3](https://cloud.githubusercontent.com/assets/4577613/8725045/4dc62d66-2bd2-11e5-8a75-4de26174be78.jpg)

**Comment by frans-ebu** [comment]
The test content was not good enough. Will recheck.

**Comment by frans-ebu** [comment]
In any case the ebutts namespace needs to be supported for this one.

**Comment by SoleneChiche** [comment]
It is!

**Comment by SoleneChiche** [comment]
Actually, it is not supporting 2 references for style! Thanks for pointing it out, I'll modify the issue and reopen.

**Comment by SoleneChiche** [comment]
It should be all right now, but still we have this issue about video stopping. If it is the result we agreed on, we can close it.

**Comment by SoleneChiche** [comment]
@frans-ebu can you check it is all good?

**Comment by frans-ebu** [comment]
I am doing that now :)

**Comment by SoleneChiche** [comment]
So now multiple reference is supported, just an other issue with linePadding. I'm closing this one.

**Comment by frans-ebu** [comment]
There are issues with linepadding, see #36
