### ISSUE TITLE
showBackground feature not implemented

### ISSUE THREAD

**Issue by SoleneChiche** [ebu/dash.js#33]
I need to add showBackground feature in the implementation, possibly at the controller level that will show or hide the region(s).

**Comment by nigelmegitt** [comment]
Just in case you really mean show or hide the region, I thought it might be worth pointing out that showBackground should only show or hide the region's background - it has no effect on the foreground text.

**Comment by SoleneChiche** [comment]
Yes sorry, that's my meaning too!

**Comment by nigelmegitt** [comment]
Ok, no problem!

**Comment by SoleneChiche** [comment]
@frans-ebu It is fixed now.

**Comment by frans-ebu** [comment]
tnx
