### ISSUE TITLE
Default colours

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#37]
(Moved the colours part from #25 to here.)

Background is now transparent, but foreground text is still black? (the idea was to make it white for now and wait for Nigel's check if we would prefer another colour).

Note black is not invalid, so this is not a bug.

**Comment by SoleneChiche** [comment]
Sorry, I'm always confuse between 255,255,255 and 0,0,0, even after all this time...

**Comment by frans-ebu** [comment]
White text is ok now, but I don't see the transparent background on the p element for test47-63 ?
