### ISSUE TITLE
Video does not resize (scale)

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#8]
In the current example the video does not resize (scale). It would be nice if it could, to allow adaptation to different screens.

**Comment by SoleneChiche** [comment]
The subtitles sizes are now calculated with the cellResolution information.

**Comment by frans-ebu** [comment]
Let's split this one into different points. Subtitles part is now in #13 

This issue is about the _video_ scaling. It scales now, but still typically shows a vertical and/or horizontal scroll bar. Could we make the video simply fit the window as large as possible without showing H/V scrollbars?

![3](https://cloud.githubusercontent.com/assets/4577613/8329238/15d2966c-1a78-11e5-9a79-cdfcc4063366.jpg)

**Comment by SoleneChiche** [comment]
I'm not sure what you mean. You want no scroll bar, and shrink the video at the infinite? 
You want the video to take the whole browser?

**Comment by frans-ebu** [comment]
Simply make the video the largest possible rectangle in the given window without causing scrollbars to show. You can set a minimum size, if desired for some reason.
