### ISSUE TITLE
[test 2] does not play

### ISSUE THREAD

**Issue by frans-ebu** [ebu/dash.js#9]
test2 fails to play properly, buffering stops almost immediately after loading the page.

**Comment by SoleneChiche** [comment]
It is normal. MP4Box does not support time overlapping and throw an error at packaging:

```
TTML: timing overlapping not supported: "begin" is 0 , last "end" was 52120. Abort.
Unsupported TTML file - only EBU-TTD is supported (root shall be "tt", got "tt")
Importing as generic TTML
```

For now we can't do anything about it.

**Comment by SoleneChiche** [comment]
Same issue as #26 I close this one
